cmake_minimum_required(VERSION 3.5)
project(px4_acc_ctrl)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(px4_msgs REQUIRED)
add_executable(velocity_tracking_node src/velocity_tracking.cpp)
ament_target_dependencies(velocity_tracking_node rclcpp px4_msgs)
install(TARGETS velocity_tracking_node DESTINATION lib/${PROJECT_NAME})
ament_package()
